require("spec_helper")

describe("Config", function()
    local Config
    local helper

    before_each(function()
        helper = require("spec_helper")
        helper.reset()
        Config = require("config")
    end)

    describe("credentials", function()
        it("returns empty strings when no credentials set", function()
            local creds = Config.getCredentials()
            assert.are.equal("", creds.email)
            assert.are.equal("", creds.password)
        end)

        it("stores and retrieves credentials", function()
            Config.setCredentials("test@example.com", "secret123")
            local creds = Config.getCredentials()
            assert.are.equal("test@example.com", creds.email)
            assert.are.equal("secret123", creds.password)
        end)

        it("overwrites existing credentials", function()
            Config.setCredentials("old@example.com", "oldpass")
            Config.setCredentials("new@example.com", "newpass")
            local creds = Config.getCredentials()
            assert.are.equal("new@example.com", creds.email)
            assert.are.equal("newpass", creds.password)
        end)
    end)

    describe("sync state", function()
        it("returns nil for unknown book", function()
            local state = Config.getLastSyncState("nonexistent")
            assert.is_nil(state)
        end)

        it("stores and retrieves sync state", function()
            Config.setLastSyncState("book1", "currently-reading", 42)
            local state = Config.getLastSyncState("book1")
            assert.are.equal("currently-reading", state.status)
            assert.are.equal(42, state.percentage)
            assert.truthy(state.timestamp)
        end)

        it("overwrites sync state for same book", function()
            Config.setLastSyncState("book1", "currently-reading", 42)
            Config.setLastSyncState("book1", "read", 100)
            local state = Config.getLastSyncState("book1")
            assert.are.equal("read", state.status)
            assert.are.equal(100, state.percentage)
        end)

        it("maintains separate state per book", function()
            Config.setLastSyncState("book1", "currently-reading", 50)
            Config.setLastSyncState("book2", "read", 100)
            local state1 = Config.getLastSyncState("book1")
            local state2 = Config.getLastSyncState("book2")
            assert.are.equal("currently-reading", state1.status)
            assert.are.equal(50, state1.percentage)
            assert.are.equal("read", state2.status)
            assert.are.equal(100, state2.percentage)
        end)
    end)

    describe("session cookies", function()
        it("returns empty table when no cookies set", function()
            local cookies = Config.getSessionCookies()
            assert.are.same({}, cookies)
        end)

        it("stores and retrieves cookies", function()
            Config.setSessionCookies({ _storygraph_session = "abc123" })
            local cookies = Config.getSessionCookies()
            assert.are.equal("abc123", cookies._storygraph_session)
        end)
    end)

    describe("csrf token", function()
        it("returns empty string when no token set", function()
            local token = Config.getCsrfToken()
            assert.are.equal("", token)
        end)

        it("stores and retrieves token", function()
            Config.setCsrfToken("token123")
            local token = Config.getCsrfToken()
            assert.are.equal("token123", token)
        end)
    end)

    describe("clearSession", function()
        it("removes session cookies and csrf token", function()
            Config.setSessionCookies({ _storygraph_session = "abc" })
            Config.setCsrfToken("token123")
            Config.clearSession()
            local cookies = Config.getSessionCookies()
            local token = Config.getCsrfToken()
            assert.are.same({}, cookies)
            assert.are.equal("", token)
        end)
    end)

    describe("book mapping", function()
        it("returns nil for unmapped book", function()
            local mapping = Config.getBookMapping("nonexistent")
            assert.is_nil(mapping)
        end)

        it("stores and retrieves book mapping", function()
            Config.setBookMapping("isbn:123", "uuid-abc-123")
            local mapping = Config.getBookMapping("isbn:123")
            assert.are.equal("uuid-abc-123", mapping)
        end)

        it("maintains separate mappings per book", function()
            Config.setBookMapping("isbn:123", "uuid-1")
            Config.setBookMapping("isbn:456", "uuid-2")
            assert.are.equal("uuid-1", Config.getBookMapping("isbn:123"))
            assert.are.equal("uuid-2", Config.getBookMapping("isbn:456"))
        end)
    end)
end)
